# Generated by Django 5.0.2 on 2024-04-22 21:03

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_address_order_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(default=datetime.datetime(2024, 4, 22, 21, 2, 58, 240684, tzinfo=datetime.timezone.utc), max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address2',
            field=models.CharField(max_length=80),
        ),
    ]
