# Generated by Django 5.0.2 on 2024-04-22 20:47

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_address_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address2',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='town_or_city',
            field=models.CharField(default='', max_length=40),
        ),
    ]
