# Generated by Django 5.0.2 on 2024-04-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_address_user_alter_address_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(default='1', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
