# Generated by Django 5.0.2 on 2024-04-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_address_user_alter_address_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
