# Generated by Django 5.0.3 on 2024-03-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_image_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
